name: Тесты

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Поставить зависимости
        run: pip install --disable-pip-version-check -q -r requirements.txt

      - name: Прогнать тесты
        run: python -m unittest discover -s tests -v
